case 	:=  	    \
		rr_v1	    \
		rr_pri_v1


SRC_rr_v1       =  \
		../../base/source/LDL_bin2hot_v1.sv      \
		../../base/source/LDL_hot2bin_pri_v1.sv  \
		../source/LDL_rr_v1.sv        \
	    ./tb/LDL_rr_v1_tb.sv

SRC_rr_pri_v1   =  \
		../../base/source/LDL_bin2hot_v1.sv      \
		../../base/source/LDL_hot2bin_pri_v1.sv  \
		../source/LDL_rr_v1.sv        \
		../source/LDL_rr_pri_v1.sv    \
	    ./tb/LDL_rr_pri_v1_tb.sv

include ../../../script/sim.make

