module 	:=  	\
		bin2hot \
		ring_shift_left		\
		ring_shift_right	\
		pri_enc

SRC_bin2hot  =  \
		../source/LDL_bin2hot.sv      \
	    ./tb/LDL_bin2hot_tb.sv

SRC_pri_enc  =  \
		../source/LDL_pri_enc.sv      \
	    ./tb/LDL_pri_enc_tb.sv

SRC_ring_shift_left  =  \
		../source/LDL_ring_shift_left.sv      \
	    ./tb/LDL_ring_shift_left_tb.sv

SRC_ring_shift_right  =  \
		../source/LDL_ring_shift_right.sv      \
	    ./tb/LDL_ring_shift_right_tb.sv


include ../../../make.sim

