case 	:=  	\
		shift_ring_v1	\
		bin2hot_v1 		\
		hot2bin_pri_v1

SRC_bin2hot_v1  =       \
		../source/LDL_bin2hot_v1.sv         \
	    ./tb/LDL_bin2hot_v1_tb.sv

SRC_hot2bin_pri_v1  =   \
		../source/LDL_hot2bin_pri_v1.sv     \
	    ./tb/LDL_hot2bin_pri_v1_tb.sv

SRC_shift_ring_v1  =    \
		../source/LDL_shift_ring_v1.sv      \
	    ./tb/LDL_shift_ring_v1_tb.sv


include ../../../script/sim.make

