module 	:=  	\
		ring_shift		\
		bin2hot 		\
		hot2bin_pri

SRC_bin2hot  =  \
		../source/LDL_bin2hot.sv      	\
	    ./tb/LDL_bin2hot_tb.sv

SRC_hot2bin_pri  =  \
		../source/LDL_hot2bin_pri.sv     \
	    ./tb/LDL_hot2bin_pri_tb.sv

SRC_ring_shift  =  \
		../source/LDL_ring_shift.sv \
	    ./tb/LDL_ring_shift_tb.sv


include ../../../make.sim

