module 	:=  	\
		round


SRC_round    =  \
		../../base/source/LDL_bin2hot.sv      \
		../../base/source/LDL_pri_enc.sv      \
		../../base/source/LDL_ring_shift_right.sv      \
		../source/LDL_round.sv        \
	    ./tb/LDL_round_tb.sv

include ../../../make.sim

