module 	:=  	\
		round	\
		round_pri


SRC_round    =  \
		../../base/source/LDL_bin2hot.sv      \
		../../base/source/LDL_hot2bin_pri.sv  \
		../../base/source/LDL_ring_shift.sv   \
		../source/LDL_round.sv        \
	    ./tb/LDL_round_tb.sv

SRC_round_pri    =  \
		../../base/source/LDL_bin2hot.sv      \
		../../base/source/LDL_hot2bin_pri.sv  \
		../../base/source/LDL_ring_shift.sv   \
		../source/LDL_round.sv        \
		../source/LDL_round_pri.sv    \
	    ./tb/LDL_round_pri_tb.sv

include ../../../make.sim

