case  :=  	        \
		cdc_ring_v1_1   \
		cdc_ring_v1_2   \
		cdc_hand_v1

SRC_cdc_ring_v1_1  =    \
		../../../rtl/base/source/LDL_dff_array_v1.sv   \
		../source/LDL_cdc_buff_v1.sv    \
		../source/LDL_cdc_ring_v1.sv    \
	    ./tb/LDL_cdc_ring_v1_tb.sv

SRC_cdc_ring_v1_2  =  ${SRC_cdc_ring_v1_1}

SRC_cdc_hand_v1    =    \
		../../../rtl/base/source/LDL_dff_array_v1.sv   \
		../../../rtl/base/source/LDL_count_v1.sv   \
		../source/LDL_cdc_buff_v1.sv    \
		../source/LDL_cdc_hand_v1.sv    \
	    ./tb/LDL_cdc_hand_v1_tb.sv

include ../../../script/sim.make

