module 	:=  	\
		cdc_bus_1	\
		cdc_bus_2

SRC_cdc_bus_1    =  \
		../source/LDL_cdc_bit.sv     \
		../source/LDL_cdc_bus.sv     \
	    ./tb/LDL_cdc_bus_tb.sv

SRC_cdc_bus_2    =  ${SRC_cdc_bus_1}

include ../../../make.sim

