case  :=  sfifo_v1  sfifo_v1_no_ahead

SRC_sfifo_v1  =  ../source/LDL_sfifo_v1.sv  \
	          ../source/LDL_fifo_ws_v1.sv   \
	          ../source/LDL_fifo_rs_v1.sv   \
	          ../../../custom/memory/source/LDL_p2ram_rs_v1.sv \
	          ./tb/LDL_sfifo_v1_tb.sv

SRC_sfifo_v1_no_ahead  =  $(SRC_sfifo_v1)

include ../../../script/sim.make

