module :=  sfifo  sfifo_no_ahead

SRC_sfifo  =  ../source/LDL_sfifo.sv      \
	          ../source/LDL_sfifo_ctr.sv  \
	          ../../../custom/memory/source/LDL_ram_p2.sv \
	          ./tb/LDL_sfifo_tb.sv

SRC_sfifo_no_ahead  =  $(SRC_sfifo)

include ../../../make.sim

